In [ ]:
import keras as ks

In [ ]:
import torch as tr

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/bank.csv")

In [ ]:
df.head(5)

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  int64
 1   credit_score      10000 non-null  int64
 2   country           10000 non-null  object
 3   gender            10000 non-null  object
 4   age               10000 non-null  int64
 5   tenure            10000 non-null  int64
 6   balance           10000 non-null  float64
 7   products_number   10000 non-null  int64
 8   credit_card       10000 non-null  int64
 9   active_member     10000 non-null  int64
 10  estimated_salary  10000 non-null  float64
 11  churn             10000 non-null  int64
dtypes: float64(2), int64(8), object(2)
memory usage: 937.6+ KB

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x= df.iloc[:,1:10]
y =df.iloc[:,11]

In [ ]:
# As gender and country are object data type then we need to create them into the dummy dataset
country=pd.get_dummies(x["country"], drop_first=True)
gender=pd.get_dummies(x['gender'], drop_first=True)

In [ ]:
x=pd.concat([x,country,gender],axis=1)
x

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,Germany,Spain,Male
0,619,France,Female,42,2,0.00,1,1,1,0,0,0
1,608,Spain,Female,41,1,83807.86,1,0,1,0,1,0
2,502,France,Female,42,8,159660.80,3,1,0,0,0,0
3,699,France,Female,39,1,0.00,2,0,0,0,0,0
4,850,Spain,Female,43,2,125510.82,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,0,0,1
9996,516,France,Male,35,10,57369.61,1,1,1,0,0,1
9997,709,France,Female,36,7,0.00,1,0,1,0,0,0
9998,772,Germany,Male,42,3,75075.31,2,1,0,1,0,1
9999,792,France,Female,28,4,130142.79,1,1,0,0,0,0

In [ ]:
#Drop Unnecessory columns ( country and gender )
x=x.drop(['country','gender'], axis=1)

In [ ]:
x

,credit_score,age,tenure,balance,products_number,credit_card,active_member,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,0,0,0
1,608,41,1,83807.86,1,0,1,0,1,0
2,502,42,8,159660.80,3,1,0,0,0,0
3,699,39,1,0.00,2,0,0,0,0,0
4,850,43,2,125510.82,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,0,0,1
9997,709,36,7,0.00,1,0,1,0,0,0
9998,772,42,3,75075.31,2,1,0,1,0,1
9999,792,28,4,130142.79,1,1,0,0,0,0

In [ ]:
#splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
 #feature Scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train =sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [ ]:
#part 2- Now we will be making ANN

In [ ]:
#importing the keras libraries and package

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU, ELU
from keras.layers import Dropout

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
samples = 500
X_train_sc = tf.random.normal((samples, 81))
y_train = tf.random.uniform((samples, ), maxval=2, dtype=tf.int32)
# Creating our model's structure
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(81,)))
model.add(Dropout(0.18))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.15))
model.add(Dense(1, activation='sigmoid'))
es = EarlyStopping(monitor='val_loss', patience=5)
# Compiling the model
model.compile(loss='bce',
              optimizer='adam',
              metrics=['binary_accuracy'])
# Fitting the model
history = model.fit(X_train_sc,
                    y_train,
                    batch_size = 32,
                    epochs = 2,
                    verbose = 0)

sequential library is responsible for
creating this typ of neural network

form creating hidden layers we need desnse library

optimizer libraries

Dropout is your regulerization parameter
when every our neural networks are fualty

In [ ]:
#initialising the ANN ( sequential library)
classifier = Sequential()

In [ ]:
#adding the input layers and the first hidden layer, using dense to create first hidden layer
classifier.add(Dense(units = 5, kernel_initializer ='he_uniform', activation='relu', input_dim=10))

In [ ]:
#to check total number of inputs we need to take in input dim
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   credit_score     10000 non-null  int64
 1   age              10000 non-null  int64
 2   tenure           10000 non-null  int64
 3   balance          10000 non-null  float64
 4   products_number  10000 non-null  int64
 5   credit_card      10000 non-null  int64
 6   active_member    10000 non-null  int64
 7   Germany          10000 non-null  uint8
 8   Spain            10000 non-null  uint8
 9   Male             10000 non-null  uint8
dtypes: float64(1), int64(6), uint8(3)
memory usage: 576.3 KB

In [ ]:
#adding the second hidding layer
classifier.add(Dense(units = 5, kernel_initializer ='he_uniform', activation='relu' ))

In [ ]:
classifier.add(Dropout(0.3))

units for hidden layer no. of neurons in the first layer selection

kernel_initilizer for weight initilization
activation -Relu for using adding activation function to the equation

In [ ]:
#Adding output layer
classifier.add(Dense(units=1, kernel_initializer ='glorot_uniform', activation ='sigmoid'))

as we know answer in last layer would be one means the customers are going to chrun (1) represented by 1 only so want 1 so we are using sigmoid function in last layer

in initail two layer we are taking relu or we can take leaky relu to avoid vanishing of gradient function but in last layer as we want so far calculation in both layer in the form of 0 or 1 so we rae snusing the sigmoid fution

In [ ]:
#compiling the ANN
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics=['accuracy'])

While compiling we are going to define waht kind of opitmizer need to be used what type of loss function we are going to use and what matrics we are looking for

As adamax is best and mostly used loss function
as we have binary output so we are looking for binary_crossentropy

if we have more than one category we will be looking for the category_crossentropy

In [ ]:
#Fitting the ANN to the training set
model_history = classifier.fit(x_train, y_train , validation_split = 0.33, batch_size = 10, epochs= 50)

Epoch 1/50
536/536 [==============================] - 4s 6ms/step - loss: 0.6196 - accuracy: 0.7936 - val_loss: 0.5612 - val_accuracy: 0.8527
Epoch 2/50
536/536 [==============================] - 2s 4ms/step - loss: 0.5262 - accuracy: 0.8403 - val_loss: 0.4933 - val_accuracy: 0.8478
Epoch 3/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4755 - accuracy: 0.8444 - val_loss: 0.4551 - val_accuracy: 0.8440
Epoch 4/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4491 - accuracy: 0.8429 - val_loss: 0.4318 - val_accuracy: 0.8470
Epoch 5/50
536/536 [==============================] - 5s 9ms/step - loss: 0.4317 - accuracy: 0.8461 - val_loss: 0.4165 - val_accuracy: 0.8459
Epoch 6/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4279 - accuracy: 0.8399 - val_loss: 0.4082 - val_accuracy: 0.8478
Epoch 7/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4169 - accuracy: 0.8457 - val_loss: 0.4010 - val_accuracy: 0.8470
Epoch 8/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4106 - accuracy: 0.8477 - val_loss: 0.3997 - val_accuracy: 0.8421
Epoch 9/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4119 - accuracy: 0.8451 - val_loss: 0.3934 - val_accuracy: 0.8493
Epoch 10/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4103 - accuracy: 0.8444 - val_loss: 0.3910 - val_accuracy: 0.8478
Epoch 11/50
536/536 [==============================] - 6s 11ms/step - loss: 0.4088 - accuracy: 0.8455 - val_loss: 0.3895 - val_accuracy: 0.8497
Epoch 12/50
536/536 [==============================] - 4s 8ms/step - loss: 0.4200 - accuracy: 0.8403 - val_loss: 0.3876 - val_accuracy: 0.8523
Epoch 13/50
536/536 [==============================] - 4s 7ms/step - loss: 0.4145 - accuracy: 0.8425 - val_loss: 0.3886 - val_accuracy: 0.8474
Epoch 14/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4096 - accuracy: 0.8462 - val_loss: 0.3889 - val_accuracy: 0.8474
Epoch 15/50
536/536 [==============================] - 3s 5ms/step - loss: 0.4141 - accuracy: 0.8416 - val_loss: 0.3873 - val_accuracy: 0.8478
Epoch 16/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4153 - accuracy: 0.8410 - val_loss: 0.3875 - val_accuracy: 0.8466
Epoch 17/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4105 - accuracy: 0.8470 - val_loss: 0.3863 - val_accuracy: 0.8504
Epoch 18/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4135 - accuracy: 0.8446 - val_loss: 0.3856 - val_accuracy: 0.8519
Epoch 19/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4021 - accuracy: 0.8468 - val_loss: 0.3858 - val_accuracy: 0.8474
Epoch 20/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4067 - accuracy: 0.8464 - val_loss: 0.3830 - val_accuracy: 0.8497
Epoch 21/50
536/536 [==============================] - 3s 5ms/step - loss: 0.4074 - accuracy: 0.8442 - val_loss: 0.3810 - val_accuracy: 0.8538
Epoch 22/50
536/536 [==============================] - 3s 5ms/step - loss: 0.4028 - accuracy: 0.8457 - val_loss: 0.3836 - val_accuracy: 0.8485
Epoch 23/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4078 - accuracy: 0.8474 - val_loss: 0.3831 - val_accuracy: 0.8508
Epoch 24/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4143 - accuracy: 0.8438 - val_loss: 0.3824 - val_accuracy: 0.8508
Epoch 25/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4075 - accuracy: 0.8453 - val_loss: 0.3835 - val_accuracy: 0.8482
Epoch 26/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4079 - accuracy: 0.8446 - val_loss: 0.3811 - val_accuracy: 0.8535
Epoch 27/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4088 - accuracy: 0.8466 - val_loss: 0.3841 - val_accuracy: 0.8493
Epoch 28/50
536/536 [==============================] - 3s 5ms/step - loss: 0.4086 - accuracy: 0.8431 - val_loss: 0.3809 - val_accuracy: 0.8493
Epoch 29/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4075 - accuracy: 0.8462 - val_loss: 0.3814 - val_accuracy: 0.8497
Epoch 30/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4077 - accuracy: 0.8442 - val_loss: 0.3776 - val_accuracy: 0.8576
Epoch 31/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4110 - accuracy: 0.8429 - val_loss: 0.3791 - val_accuracy: 0.8538
Epoch 32/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4111 - accuracy: 0.8431 - val_loss: 0.3828 - val_accuracy: 0.8474
Epoch 33/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4131 - accuracy: 0.8425 - val_loss: 0.3834 - val_accuracy: 0.8493
Epoch 34/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4079 - accuracy: 0.8455 - val_loss: 0.3807 - val_accuracy: 0.8504
Epoch 35/50
536/536 [==============================] - 3s 5ms/step - loss: 0.4025 - accuracy: 0.8468 - val_loss: 0.3797 - val_accuracy: 0.8516
Epoch 36/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4085 - accuracy: 0.8429 - val_loss: 0.3827 - val_accuracy: 0.8478
Epoch 37/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4087 - accuracy: 0.8419 - val_loss: 0.3802 - val_accuracy: 0.8516
Epoch 38/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4063 - accuracy: 0.8447 - val_loss: 0.3780 - val_accuracy: 0.8519
Epoch 39/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4090 - accuracy: 0.8434 - val_loss: 0.3797 - val_accuracy: 0.8519
Epoch 40/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4116 - accuracy: 0.8431 - val_loss: 0.3803 - val_accuracy: 0.8493
Epoch 41/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4047 - accuracy: 0.8492 - val_loss: 0.3782 - val_accuracy: 0.8519
Epoch 42/50
536/536 [==============================] - 3s 5ms/step - loss: 0.4080 - accuracy: 0.8462 - val_loss: 0.3793 - val_accuracy: 0.8516
Epoch 43/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4092 - accuracy: 0.8433 - val_loss: 0.3776 - val_accuracy: 0.8523
Epoch 44/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4074 - accuracy: 0.8447 - val_loss: 0.3790 - val_accuracy: 0.8535
Epoch 45/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4040 - accuracy: 0.8459 - val_loss: 0.3777 - val_accuracy: 0.8535
Epoch 46/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4081 - accuracy: 0.8455 - val_loss: 0.3775 - val_accuracy: 0.8542
Epoch 47/50
536/536 [==============================] - 2s 3ms/step - loss: 0.4071 - accuracy: 0.8449 - val_loss: 0.3772 - val_accuracy: 0.8523
Epoch 48/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4155 - accuracy: 0.8399 - val_loss: 0.3813 - val_accuracy: 0.8489
Epoch 49/50
536/536 [==============================] - 3s 5ms/step - loss: 0.4071 - accuracy: 0.8447 - val_loss: 0.3789 - val_accuracy: 0.8535
Epoch 50/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4056 - accuracy: 0.8440 - val_loss: 0.3784 - val_accuracy: 0.8516

In [ ]:
#Part -3 Making the prediction and evaluating the model

In [ ]:
#Predicting the test set result
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

In [ ]:
#making the confusion matrics
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

In [ ]:
#calculate the accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred )